import { Router } from 'express';
import * as ic from '../controllers/inquiryController';
import { protect } from '../middlewares/authMiddleware';
const router = Router();
router.post('/', ic.createInquiry);
router.get('/', protect, ic.getInquiries);
router.get('/export/csv', protect, ic.exportInquiriesCSV);
router.get('/:id', protect, ic.getInquiryById);
router.put('/:id', protect, ic.updateInquiryStatus);
router.delete('/:id', protect, ic.deleteInquiry);
export default router;
